archiv/urls.py
from django.conf.urls import url
from . import views
from . import tei_views

from archeutils import views as arche_views


app_name = 'archiv'

urlpatterns = [
    url(
        r'^ids$',
        arche_views.get_ids,
        name='get_ids'
    ),
    url(
        r'^arche-title-img$',
        arche_views.get_title_img,
        name='arche_title_img'
    ),
    url(
        r'^arche-md$',
        arche_views.project_as_arche_graph,
        name='arche_md'
    ),
    url(
        r'^archresource/arche/(?P<pk>[0-9]+)$',
        arche_views.res_as_arche_graph,
        name='arche_res'
    ),
    url(
        r'^archresource/$',
        views.ArchResourceListView.as_view(),
        name='archresource_browse'
    ),
    url(
        r'^subject-cloud/$',
        views.subject_cloud,
        name='subject-cloud'
    ),
    url(
        r'^schlagworte/$',
        views.SchlagwortList.as_view(),
        name='schlagworte'
    ),
    url(
        r'^archresource/detail/(?P<pk>[0-9]+)$',
        views.ArchResourceDetailView.as_view(),
        name='archresource_detail'
    ),
    url(
        r'^archresource/create/$',
        views.ArchResourceCreate.as_view(),
        name='archresource_create'
    ),
    url(
        r'^archresource/edit/(?P<pk>[0-9]+)$',
        views.ArchResourceUpdate.as_view(),
        name='archresource_edit'
    ),
    url(
        r'^archresource/delete/(?P<pk>[0-9]+)$',
        views.ArchResourceDelete.as_view(),
        name='archresource_delete'),
    url(
        r'^archresource/xml-tei/(?P<pk>[0-9]+)$',
        tei_views.archres_as_tei,
        name='archresource_xml'
    ),
]

netviz/urls.py
from django.urls import include, path
from . import views

app_name = "netviz"

urlpatterns = [
    path('graph/<app_name>/<model_name>/<pk>', views.graph_data, name='graph'),
    path('graph/<app_name>/<model_name>', views.qs_graph_data, name='qs_as_graph'),
    path('cached/<app_name>/<model_name>', views.cashed_graph_data, name='cached_graph'),
    path('preview/<app_name>/<model_name>', views.preview_graph_data, name='preview_graph'),
    path('<app_name>/<model_name>', views.CachedNetvizView.as_view(), name='cached_graph_html'),
]

vocabs/urls.py
from django.conf.urls import url
from . import views
from . import import_views
from . import dal_views
from .models import SkosLabel, SkosConcept, SkosConceptScheme

app_name = 'vocabs'


urlpatterns = [
    url(r'^$', views.SkosConceptListView.as_view(), name='skosconcept_list'),
    url(r'^concepts/browse/$', views.SkosConceptListView.as_view(), name='browse_vocabs'),
    url(r'^import/$', import_views.import_skos, name='skos_import'),
    url(r'^import-from-csv/$', import_views.import_csv, name='skos_csv_import'),
    url(r'^(?P<pk>[0-9]+)$', views.SkosConceptDetailView.as_view(), name='skosconcept_detail'),
    url(r'^create/$', views.SkosConceptCreate.as_view(), name='skosconcept_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.SkosConceptUpdate.as_view(), name='skosconcept_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SkosConceptDelete.as_view(), name='skosconcept_delete'),
    url(r'^scheme/$', views.SkosConceptSchemeListView.as_view(), name='skosconceptscheme_list'),
    url(
        r'^scheme/(?P<pk>[0-9]+)$', views.SkosConceptSchemeDetailView.as_view(),
        name='skosconceptscheme_detail'),
    url(
        r'^scheme/create/$', views.SkosConceptSchemeCreate.as_view(),
        name='skosconceptscheme_create'),
    url(
        r'^scheme/update/(?P<pk>[0-9]+)$', views.SkosConceptSchemeUpdate.as_view(),
        name='skosconceptscheme_update'),
    url(r'^label/$', views.SkosLabelListView.as_view(), name='skoslabel_list'),
    url(
        r'^label/(?P<pk>[0-9]+)$', views.SkosLabelDetailView.as_view(),
        name='skoslabel_detail'),
    url(
        r'^label/create/$', views.SkosLabelCreate.as_view(),
        name='skoslabel_create'),
    url(
        r'^label/update/(?P<pk>[0-9]+)$', views.SkosLabelUpdate.as_view(),
        name='skoslabel_update'),
]

vocabs/forms.py
from dal import autocomplete
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Div, MultiField, HTML
from crispy_forms.bootstrap import *
from .models import SkosConcept, SkosConceptScheme, SkosLabel


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'search'))


class UploadFileForm(forms.Form):
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'import'),)


class SkosConceptFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SkosConceptFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Accordion(
                AccordionGroup(
                    'Basic search options',
                    'pref_label',
                    css_id="basic_search_fields"
                ),
                AccordionGroup(
                    'Advanced search',
                    'scheme',
                    css_id="more"
                    ),
                )
            )


class SkosConceptForm(forms.ModelForm):
    class Meta:
        model = SkosConcept
        fields = "__all__"
        widgets = {
            'other_label': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skoslabel-autocomplete'
            ),
            'skos_broader': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_narrower': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_related': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_broadmatch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_exactmatch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_closematch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'scheme': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconceptscheme-autocomplete'
            )
        }

    def __init__(self, *args, **kwargs):
        super(SkosConceptForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosConceptSchemeForm(forms.ModelForm):
    class Meta:
        model = SkosConceptScheme
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SkosConceptSchemeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosLabelForm(forms.ModelForm):
    class Meta:
        model = SkosLabel
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SkosLabelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)

vocabs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django_tables2 import SingleTableView, RequestConfig
from .models import SkosConcept, SkosConceptScheme, SkosLabel
from .forms import *
from .tables import SkosConceptTable
from .filters import SkosConceptListFilter


class GenericListView(SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'
    paginate_by = 25
    template_name = 'vocabs/generic_list.html'

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_queryset(self, **kwargs):
        qs = super(GenericListView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by}).configure(table)
        return table

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        context['docstring'] = "{}".format(self.model.__doc__)
        if self.model.__name__.endswith('s'):
            context['class_name'] = "{}".format(self.model.__name__)
        else:
            context['class_name'] = "{}s".format(self.model.__name__)
        try:
            context['get_arche_dump'] = self.model.get_arche_dump()
        except AttributeError:
            context['get_arche_dump'] = None
        try:
            context['create_view_link'] = self.model.get_createview_url()
        except AttributeError:
            context['create_view_link'] = None
        return context


class SkosConceptListView(GenericListView):
    model = SkosConcept
    table_class = SkosConceptTable
    filter_class = SkosConceptListFilter
    formhelper_class = SkosConceptFormHelper
    init_columns = ['id', 'broader_concept', 'pref_label', 'all_schemes']

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosConceptListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosConceptDetailView(DetailView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_detail.html'


class SkosConceptCreate(CreateView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_create.html'
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptCreate, self).dispatch(*args, **kwargs)


class SkosConceptUpdate(UpdateView):

    model = SkosConcept
    form_class = SkosConceptForm
    template_name = 'vocabs/skosconcept_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptUpdate, self).dispatch(*args, **kwargs)


class SkosConceptDelete(DeleteView):
    model = SkosConcept
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_vocabs')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptDelete, self).dispatch(*args, **kwargs)


#####################################################
#   ConceptScheme
#####################################################


class SkosConceptSchemeDetailView(DetailView):

    model = SkosConceptScheme
    template_name = 'vocabs/skosconceptscheme_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeDetailView, self).get_context_data(**kwargs)
        context["concepts"] = SkosConcept.objects.filter(scheme=self.kwargs.get('pk'))
        return context


class SkosConceptSchemeListView(ListView):

    model = SkosConceptScheme
    template_name = 'vocabs/skosconceptscheme_list.html'


class SkosConceptSchemeCreate(CreateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm
    template_name = 'vocabs/skosconceptscheme_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeCreate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeUpdate(UpdateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm
    template_name = 'vocabs/skosconceptscheme_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeUpdate, self).dispatch(*args, **kwargs)


###################################################
# SkosLabel
###################################################


class SkosLabelDetailView(DetailView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_detail.html'


class SkosLabelListView(ListView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_list.html'


class SkosLabelCreate(CreateView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_create.html'
    form_class = SkosLabelForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelCreate, self).dispatch(*args, **kwargs)


class SkosLabelUpdate(UpdateView):

    model = SkosLabel
    form_class = SkosLabelForm
    template_name = 'vocabs/skoslabel_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelUpdate, self).dispatch(*args, **kwargs)

vocabs/templates/vocabs/confirm_delete.html
{% extends "vocabs/plain_for_delete.html" %}
{% block content %}
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header"><h3 class="modal-title">Confirm delete</h3></div>
            <div class="modal-body">
                <form action="" method="post">{% csrf_token %}
                    <h4>Are you sure you want to delete :<br /> <strong>{{ object }}</strong> ?</h4><br />
                    <a href="javascript:history.back()"><input class="btn btn-default" type="button" value="cancel"/></a>
                    <input  class="btn btn-danger" type="submit" value="yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript">
        $(window).load(function(){
            $('#myModal').modal('show');
        });
    </script>
{% endblock scripts %}

vocabs/templates/vocabs/import_skos.html
{% extends "webpage/base.html" %}
{% block Title %} Import SKOS {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Import SKOS</h1>
    </div>
    <div class="card-body">
        <h2 style="text-align: center;">{{ worked }}</h2><br />
        {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

vocabs/templates/vocabs/plain_for_delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="A little Application">
        <meta name="author" content="ACDH">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
        <!-- custom css -->
        <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" />
        <!-- custom font -->
        <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet">
    </head>
    <body  role="document">
        <div id="content" class="container">
            {% block content %}
            {% endblock %}
        </div>
        <div id="footer">
            <div class="container"></div>
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

vocabs/templates/vocabs/skosconcept_create.html
{% extends "webpage/base.html" %}
{% block Title %} Create/Modify Concept {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>Create/Edit skos:Concept</h1>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

vocabs/templates/vocabs/skosconcept_detail.html
{% extends "webpage/base.html" %}
{% block title %}{{ object }}{% endblock %}
{% block scriptHeader %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>
    <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/three@latest/build/three.min.js"></script>
    <script crossorigin src="https://unpkg.com/@acdh/network-visualization@0/lib/network-visualization.umd.js"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/wordcloud.js"></script>
{% endblock scriptHeader %}
{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skosconcept_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small><a href="{{ object.get_listview_url }}">Schlagwort</a>:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skosconcept_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skosconcept_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skosconcept_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-2">
                    {% if object.broader_concept %}
                        <div class="card">
                            <div class="card-header">übergeordnetes Konzept</div>
                            <div class="card-body">
                                {% if object.broader_concept %}
                                    <a href="{{ object.broader_concept.get_absolute_url }}">{{ object.broader_concept }}</a>
                                {% endif %}
                                {% for x in object.get_broader %}
                                    <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                    {% if object.other_label.all %}
                    <div class="card">
                        <div class="card-header">Synonym(e)</div>
                        <div class="card-body">
                            {% for x in object.other_label.all %}
                                <li>
                                    {{ x.label }}
                                </li>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% if object.narrower_concepts.all %}
                        <div class="card">
                            <div class="card-header">untergeordnete Konzepte</div>
                            <div class="card-body">
                                {% for x in object.narrower_concepts.all %}
                                    <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-header">
                            <h4>verbundene Objekte</h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-hover">
                                {% if object.subject_norm_of.all %}
                                    <tr>
                                        <td>
                                            Dokumente
                                        </td>
                                        <td>
                                            {% for x in object.subject_norm_of.all %}
                                                <li>
                                                    <a href="{{x.get_absolute_url }}">{{ x }}</a>
                                                </li>
                                            {% endfor %}
                                        </td>
                                    </tr>
                                {% endif %}
                                {% if object.definition %}
                                    <tr>
                                        <td>skos:definition | @{{ object.definition_lang }}</td>
                                        <td>{{ object.definition }}</td>
                                    </tr>
                                {% endif %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Netzwerk</h4>
                        </div>
                        <div class="card-body">
                            <div id="visualization" style="position: relative; height: 400px; background: #fafafa;"></div>
                            <script type="text/javascript">
                                const visCard = document.getElementById('visualization')
                                var spinner = new Spinner().spin();
                                visCard.appendChild(spinner.el);
                                fetch("{% url 'netviz:graph' app_name='vocabs' model_name='skosconcept' pk=object.id %}")
                                  .then(response => response.json())
                                  .then((graph) => {
                                    // jsonData is parsed json object received from url
                                    ReactDOM.render(
                                        React.createElement(NetworkVisualization.SelectionControls, {graph}),
                                        document.getElementById('visualization')
                                    )
                                  })
                                  .catch((error) => {
                                    // handle your errors here
                                    console.error(error)
                                  })
                                // const graph = JSON.parse(document.getElementById('netviz-data').textContent);

                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

vocabs/templates/vocabs/skosconcept_filter.html
{% extends "vocabs/generic_list.html" %}
{% block list_title %}Browse SkosConcepts{% endblock %}
{% block create_button %}
{% if user.is_authenticated %}
<div>
    <a class ="btn btn-primary"  href="{% url 'vocabs:skosconcept_create' %}">
        create new concept
    </a>
</div>
{% endif %}
{% endblock %}
{% block reset_button %}
    <a class ="btn btn-outline-secondary" href="{% url 'vocabs:browse_vocabs' %}">reset search</a>
{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_create.html
{% extends "webpage/base.html" %}
{% block Title %} Create/Modify Concept Scheme {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="card">
    <div class="card-header">
        <h1>Create/Edit Concept Scheme</h1>
    </div>
    <div class="card-body">
         {% crispy form %}
    </div>
</div>
</div>
{% endblock content %}

vocabs/templates/vocabs/skosconceptscheme_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>
                {{ object.namespace }}:{{ object.dc_title}}<br/> <small>a skos:ConceptScheme</small>
                {% if user.is_authenticated %}
                  <a href="{% url 'vocabs:skosconceptscheme_update' pk=object.id %}">
                      <i class="far fa-edit" title="edit"></i>
                  </a>
                {% endif %}
            </h1>
            <small>dct:creator</small> {{ object.dct_creator }}<br />
        </div>
        <div class="card-body">
          {% for x in concepts %}
              <li>
                  <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a>
              </li>
          {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>Concept Schemes</h1>
            <div>
                <a class="btn btn-outline-secondary" href="{% url 'vocabs:skosconceptscheme_create' %}" role="button">
                    Create Concept Scheme
                </a>
            </div>
            <br />
        </div>
        <div class="card-body">
            {% for object in object_list %}
                <li>
                    <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.id %}">
                        {{ object }}
                    </a>
                </li>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_create.html
{% extends "webpage/base.html" %}
{% block Title %}Create/Modify Label{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>Create/Edit Label</h1>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

vocabs/templates/vocabs/skoslabel_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>
                {{ object }}<br/> <small>skos:prefLabel</small>
                {% if user.is_authenticated %}
                    <a href="{% url 'vocabs:skoslabel_update' pk=object.id %}">
                        <i class="far fa-edit" title="edit"></i>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>Label</th>
                    <td>{{ object.label }}</td>
                </tr>
                <tr>
                    <th>Label type</th>
                    <td>{{ object.label_type }}</td>
                </tr>
                <tr>
                    <th>IsoCode</th>
                    <td>{{ object.isoCode }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>Labels</h1>
            <div>
                <a class="btn btn-outline-secondary" href="{% url 'vocabs:skoslabel_create' %}" role="button">
                    Create Label
                </a>
            </div>
            <br />
        </div>
        <div class="card-body">
            {% for object in object_list %}
                <li><a href="{% url 'vocabs:skoslabel_detail' pk=object.id %}">{{ object }}</a></li>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}