archiv/urls.py
from django.conf.urls import url
from . import views
from . import tei_views

from archeutils import views as arche_views


app_name = 'archiv'

urlpatterns = [
    url(
        r'^ids$',
        arche_views.get_ids,
        name='get_ids'
    ),
    url(
        r'^arche-title-img$',
        arche_views.get_title_img,
        name='arche_title_img'
    ),
    url(
        r'^arche-md$',
        arche_views.project_as_arche_graph,
        name='arche_md'
    ),
    url(
        r'^archresource/arche/(?P<pk>[0-9]+)$',
        arche_views.res_as_arche_graph,
        name='arche_res'
    ),
    url(
        r'^archresource/$',
        views.ArchResourceListView.as_view(),
        name='archresource_browse'
    ),
    url(
        r'^subject-cloud/$',
        views.subject_cloud,
        name='subject-cloud'
    ),
    url(
        r'^schlagworte/$',
        views.SchlagwortList.as_view(),
        name='schlagworte'
    ),
    url(
        r'^archresource/detail/(?P<pk>[0-9]+)$',
        views.ArchResourceDetailView.as_view(),
        name='archresource_detail'
    ),
    url(
        r'^archresource/create/$',
        views.ArchResourceCreate.as_view(),
        name='archresource_create'
    ),
    url(
        r'^archresource/edit/(?P<pk>[0-9]+)$',
        views.ArchResourceUpdate.as_view(),
        name='archresource_edit'
    ),
    url(
        r'^archresource/delete/(?P<pk>[0-9]+)$',
        views.ArchResourceDelete.as_view(),
        name='archresource_delete'),
    url(
        r'^archresource/xml-tei/(?P<pk>[0-9]+)$',
        tei_views.archres_as_tei,
        name='archresource_xml'
    ),
]

entities/urls.py
from django.conf.urls import url
from . import views

app_name = 'entities'

urlpatterns = [
    url(
        r'^person/$',
        views.PersonListView.as_view(),
        name='person_browse'
    ),
    url(
        r'^person/detail/(?P<pk>[0-9]+)$',
        views.PersonDetailView.as_view(),
        name='person_detail'
    ),
    url(
        r'^person/create/$',
        views.PersonCreate.as_view(),
        name='person_create'
    ),
    url(
        r'^person/edit/(?P<pk>[0-9]+)$',
        views.PersonUpdate.as_view(),
        name='person_edit'
    ),
    url(
        r'^person/delete/(?P<pk>[0-9]+)$',
        views.PersonDelete.as_view(),
        name='person_delete'),
    url(
        r'^place/$',
        views.PlaceListView.as_view(),
        name='place_browse'
    ),
    url(
        r'^place/detail/(?P<pk>[0-9]+)$',
        views.PlaceDetailView.as_view(),
        name='place_detail'
    ),
    url(
        r'^place/create/$',
        views.PlaceCreate.as_view(),
        name='place_create'
    ),
    url(
        r'^place/edit/(?P<pk>[0-9]+)$',
        views.PlaceUpdate.as_view(),
        name='place_edit'
    ),
    url(
        r'^place/delete/(?P<pk>[0-9]+)$',
        views.PlaceDelete.as_view(),
        name='place_delete'),
    url(
        r'^institution/$',
        views.InstitutionListView.as_view(),
        name='institution_browse'
    ),
    url(
        r'^institution/detail/(?P<pk>[0-9]+)$',
        views.InstitutionDetailView.as_view(),
        name='institution_detail'
    ),
    url(
        r'^institution/create/$',
        views.InstitutionCreate.as_view(),
        name='institution_create'
    ),
    url(
        r'^institution/edit/(?P<pk>[0-9]+)$',
        views.InstitutionUpdate.as_view(),
        name='institution_edit'
    ),
    url(
        r'^institution/delete/(?P<pk>[0-9]+)$',
        views.InstitutionDelete.as_view(),
        name='institution_delete'),
]

netviz/urls.py
from django.urls import include, path
from . import views

app_name = "netviz"

urlpatterns = [
    path('graph/<app_name>/<model_name>/<pk>', views.graph_data, name='graph'),
    path('graph/<app_name>/<model_name>', views.qs_graph_data, name='qs_as_graph'),
    path('cached/<app_name>/<model_name>', views.cashed_graph_data, name='cached_graph'),
    path('preview/<app_name>/<model_name>', views.preview_graph_data, name='preview_graph'),
    path('<app_name>/<model_name>', views.CachedNetvizView.as_view(), name='cached_graph_html'),
]

entities/models.py
import re
import lxml.etree as ET
from django.db import models
from django.urls import reverse
from django.conf import settings
from idprovider.models import IdProvider
from AcdhArcheAssets.uri_norm_rules import get_normalized_uri

from browsing.browsing_utils import model_to_dict

from . utils import get_coordinates
from tei.entities_utils import person_to_tei, org_to_tei, place_to_tei

ARCHE_BASE_URL = getattr(settings, 'ARCHE_BASE_URL', 'https://id.acdh.oeaw.ac.at/MYPROJECT')


INSTITUTION_TYPES = (
    ('Partei', 'Partei'),
    ('Archiv', 'Archiv'),
    ('Sonstiges', 'Sonstiges'),
)


class Place(IdProvider):
    """Holds information about entities."""
    PLACE_TYPES = (
        ("city", "city"),
        ("country", "country")
    )
    name = models.CharField(
        max_length=250, blank=True, help_text="Normalized name"
    )
    alt_names = models.TextField(
        blank=True, verbose_name="Alternative Bezeichnungen",
        help_text="Im Falle mehrerer Einträge, diese bitte mit ';' trennen"
    )
    geonames_id = models.CharField(
        max_length=500, blank=True,
        verbose_name="Geonames-ID",
        help_text="z.B.: http://www.geonames.org/2773493/bad-kreuzen.html"
    )
    lat = models.DecimalField(
        max_digits=20, decimal_places=12,
        blank=True, null=True
    )
    lng = models.DecimalField(
        max_digits=20, decimal_places=12, blank=True, null=True
    )
    part_of = models.ForeignKey(
        "Place", null=True, blank=True,
        help_text="A place (country) this place is part of.",
        related_name="has_child",
        on_delete=models.SET_NULL
    )
    place_type = models.CharField(
        choices=PLACE_TYPES, null=True, blank=True, max_length=50
    )

    def get_geonames_url(self):
        if self.geonames_id.startswith('ht') and self.geonames_id.endswith('.html'):
            return self.geonames_id
        else:
            return "http://www.geonames.org/{}".format(self.geonames_id)

    def get_geonames_rdf(self):
        try:
            number = re.findall(r'\d+', str(self.geonames_id))[0]
            return number
        except Exception as e:
            return None

    def get_canonic_rdf(self):
        if self.get_geonames_rdf() is not None:
            can_uri = f"http://sws.geonames.org/{self.get_geonames_rdf()}/"
        else:
            can_uri = None
        return can_uri
    
    def arche_id(self):
        if self.get_canonic_rdf() is not None:
            return get_normalized_uri(f"{self.get_canonic_rdf()}")
        else:
            return f"{ARCHE_BASE_URL}/place/{self.id}"

    def save(self, *args, **kwargs):
        if self.geonames_id:
            new_id = self.get_geonames_url()
            self.geonames_id = new_id
        if self.get_geonames_rdf() and not self.lat:
            coords = get_coordinates(self.get_geonames_rdf())
            if coords:
                self.lat = coords['lat']
                self.lng = coords['lng']
        super(Place, self).save(*args, **kwargs)

    @classmethod
    def get_listview_url(self):
        return reverse('entities:place_browse')

    @classmethod
    def get_createview_url(self):
        return reverse('entities:place_create')

    def get_absolute_url(self):
        return reverse('entities:place_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('entities:place_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('entities:place_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'entities:place_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'entities:place_detail',
                kwargs={'pk': prev.first().id}
            )
        return False

    def field_dict(self):
        return model_to_dict(self)

    def as_tei_node(self):
        return place_to_tei(self)

    def as_tei(self):
        return ET.tostring(self.as_tei_node(), pretty_print=True, encoding='UTF-8')

    def __str__(self):
        return "{}".format(self.name)


class Institution(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True)
    written_name = models.CharField(
        verbose_name="Name",
        max_length=300, blank=True
    )
    authority_url = models.CharField(max_length=300, blank=True)
    alt_names = models.TextField(
        blank=True, verbose_name="Alternative Bezeichnungen",
        help_text="Im Falle mehrerer Einträge, diese bitte mit ';' trennen"
    )
    abbreviation = models.CharField(
        max_length=300, blank=True, verbose_name="Abkürzung"
    )
    location = models.ForeignKey(
        Place, blank=True, null=True, on_delete=models.SET_NULL,
        verbose_name="Hauptstandort", related_name="location_of_institution"
    )
    parent_institution = models.ForeignKey(
        'Institution', blank=True, null=True, related_name='children_institutions',
        on_delete=models.SET_NULL, verbose_name="Teil von Institution",
        help_text="provide some"
    )
    comment = models.TextField(
        blank=True, null=True, verbose_name="Anmerkung, Kommentar",
        help_text="provide some"
    )
    institution_type = models.CharField(
        max_length=300, blank=True, verbose_name='Art der Institution',
        help_text="Partei, Archiv, sonstiges", choices=INSTITUTION_TYPES, default="Sonstiges"
    )

    def as_tei_node(self):
        return org_to_tei(self)

    def as_tei(self):
        return ET.tostring(self.as_tei_node(), pretty_print=True, encoding='UTF-8')

    @classmethod
    def get_listview_url(self):
        return reverse('entities:institution_browse')

    @classmethod
    def get_createview_url(self):
        return reverse('entities:institution_create')

    def get_absolute_url(self):
        return reverse('entities:institution_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('entities:institution_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('entities:institution_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'entities:institution_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'entities:institution_detail',
                kwargs={'pk': prev.first().id}
            )
        return False

    def field_dict(self):
        return model_to_dict(self)

    def __str__(self):
        return "{}".format(self.written_name)


class Person(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True)
    written_name = models.CharField(
        max_length=300, blank=True
    )
    forename = models.CharField(
        max_length=300, blank=True,
        verbose_name="Vorname"
    )
    name = models.CharField(
        max_length=300, blank=True,
        verbose_name="Nachname"
    )
    acad_title = models.CharField(
        verbose_name="Akademische Titel",
        max_length=300, blank=True
    )
    alt_names = models.TextField(
        blank=True, verbose_name="Alternative Bezeichnungen",
        help_text="Im Falle mehrerer Einträge, diese bitte mit ';' trennen"
    )
    belongs_to_institution = models.ManyToManyField(
        Institution, blank=True,
        related_name="has_member",
    )
    belongs_to_party = models.ForeignKey(
        Institution, blank=True, null=True, related_name="has_party_member",
        on_delete=models.SET_NULL
    )
    place_of_birth = models.ForeignKey(
        Place, blank=True, null=True, related_name="is_birthplace",
        verbose_name="Geburtsort",
        on_delete=models.SET_NULL
    )
    date_of_birth = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True,
        verbose_name="Geburtsdatum",
        help_text="YYYY-MM-DD"
    )
    date_of_birth_written = models.CharField(
        verbose_name="ungefähres Geburtsdatum",
        max_length=300, blank=True
    )
    place_of_death = models.ForeignKey(
        Place, blank=True, null=True,
        verbose_name="Todesort",
        related_name="is_deathplace",
        on_delete=models.SET_NULL
    )
    date_of_death = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True,
        verbose_name="Todesdatum",
        help_text="YYYY-MM-DD"
    )
    date_of_death_written = models.CharField(
        verbose_name="ungefähres Sterbedatum",
        max_length=300, blank=True
    )
    authority_url = models.CharField(
        max_length=300, blank=True,
        verbose_name="GND-URL (oder Wikipedia)",
        help_text="https://portal.dnb.de/ oder https://de.wikipedia.org/"
    )
    comment = models.TextField(blank=True, null=True)
    biography = models.TextField(
        blank=True, null=True, verbose_name="biographische Anmerkungen",
        help_text="Weitere biographische Anmerkungen zur Person"
    )
    funktion = models.TextField(
        blank=True, null=True, verbose_name="Funktion",
        help_text="Funktionen, Tätigkeiten, Ämter"
    )
    quelle = models.TextField(
        blank=True, null=True, verbose_name="Quellen",
        help_text="Quellen"
    )
    type_of_person = models.CharField(
        max_length=300, blank=True, verbose_name='Art der Person',
        help_text="provide some"
    )

    class Meta:
        ordering = ['name']
    
    def arche_id(self):
        if "d-nb.info/gnd/" in self.authority_url:

entities/templates/entities/edit_places.html
{% extends "webpage/base.html" %}
{% load static %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
    include 'autocomplete_light/static.html
-->
<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
    <div class="col-md-4">
{% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                  <h3>{%if object %} Edit {% else %} Create {% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-default btn-block" target="_blank">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary btn-block" type="submit" value="Save" />
                    {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'entities:place_delete' pk=object.id %}">delete</a>
                    {% endif %}
                </form>
           </div>
       </div>
{% if object %}
   </div>
    <div class ="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}


<script type="text/javascript">
    $(document).ready(function(){
        $("#id_alias_name-autocomplete").after('<button id="add_aliasName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus" /></button>');
    });
    $(document).ready(function(){
        $("#id_alternative_name-autocomplete").after('<button id="add_alternativeName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus"/></button>');
    });
</script>
{% if object %}
<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 10);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
        .bindPopup(placeName)
        .openPopup();
        });
</script>


<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
        var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
       var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
       var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endif %}
{% endblock %}

entities/templates/entities/institution_detail.html
{% extends "browsing/generic_detail.html" %}
{% load static %}
{% load leaflet_tags %}
{% load webpage_extras %}
{% block title %}{{ object }}{% endblock %}
{% block scriptHeader %}
    {% leaflet_js %}
    {% leaflet_css %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>
    <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/three@latest/build/three.min.js"></script>
    <script crossorigin src="https://unpkg.com/@acdh/network-visualization@0/lib/network-visualization.umd.js"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/wordcloud.js"></script>
{% endblock scriptHeader %}
{% block custom %}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Info</h4>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-hover">
                        {% if object.written_name %}
                        <tr>
                            <th>
                                {% get_verbose_name institution "written_name" %}
                            </th>
                            <td>
                                {{ object.written_name }}
                            </td>
                        </tr>
                        {% endif %}
                        {% if object.alt_names != 'False' %}
                        <tr>
                            <th>
                                {% get_verbose_name institution "alt_names" %}
                            </th>
                            <td>
                                {{ object.alt_names }}
                            </td>
                        </tr>
                        {% endif %}
                        {% if object.abbreviation %}
                            <tr>
                                <th>
                                    {% get_verbose_name institution "abbreviation" %}
                                </th>
                                <td>
                                    {{ object.abbreviation }}
                                </td>
                            </tr>
                        {% endif %}
                        {% if object.comment %}
                        <tr>
                            <th>
                                {% get_verbose_name institution "comment" %}
                            </th>
                            <td>
                                {{ object.comment }}
                            </td>
                        </tr>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Ort und Kontext</h4>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-hover">
                        {% if object.location %}
                            <tr>
                                <th>
                                    {% get_verbose_name institution "location" %}
                                </th>
                                <td>
                                    <a href="{{ object.location.get_absolute_url }}">
                                        {{ object.location }}
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                        {% if object.parent_institution %}
                            <tr>
                                <th>
                                    {% get_verbose_name institution "parent_institution" %}
                                </th>
                                <td>
                                    <a href="{{ object.parent_institution.get_absolute_url }}">
                                        {{ object.parent_institution }}
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                        <tr>
                            <th>
                                {% get_verbose_name institution "institution_type" %}
                            </th>
                            <td>
                                {{ object.institution_type }}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Beziehungen</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Zu Dokumenten</h4>
                        </div>
                        <div class="card-body">
                            {% if object.has_docs_archived.all %}
                                <legend>
                                    Archiviert Dokumente
                                </legend>
                                <ul>
                                    {% for x in object.has_docs_archived.all %}
                                        <li>
                                            <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            <legend>
                                Erzeuger von
                            </legend>
                            <ul>
                                {% for x in object.created_by_inst.all %}
                                    <li>
                                        <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                            <legend>
                                Erwähnt in
                            </legend>
                            <ul>
                                {% for x in object.inst_mentioned_in_res.all %}
                                    <li>
                                        <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Zu Personen</h4>
                        </div>
                        <div class="card-body">
                            <ul>
                                {% for x in object.has_member.all %}
                                    <li>
                                        <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                    </li>
                                {% endfor %}
                                {% for x in object.has_party_member.all %}
                                    <li>
                                        <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Netzwerk</h4>
                        </div>
                        <div class="card-body">
                            <div id="visualization" style="position: relative; height: 400px; background: #fafafa;"></div>
                            <script type="text/javascript">
                                const visCard = document.getElementById('visualization')
                                var spinner = new Spinner().spin();
                                visCard.appendChild(spinner.el);
                                fetch("{% url 'netviz:graph' app_name='entities' model_name='institution' pk=object.id %}")
                                  .then(response => response.json())
                                  .then((graph) => {
                                    // jsonData is parsed json object received from url
                                    ReactDOM.render(
                                        React.createElement(NetworkVisualization.SelectionControls, {graph}),
                                        document.getElementById('visualization')
                                    )
                                  })
                                  .catch((error) => {
                                    // handle your errors here
                                    console.error(error)
                                  })
                                // const graph = JSON.parse(document.getElementById('netviz-data').textContent);

                            </script>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Zu Orten</h4>
                </div>
                <div class="card-body">
                    <div class="card-body">
                            <script type="text/javascript">

                                function map_init_basic (map, options) {
                                        {% if object.location.lat %}
                                            var instLocation = "liegt in: <a href='{{ object.location.get_absolute_url }}'>{{ object.location.name }} </a>"
                                            var lat = "{{ object.location.lat }}"
                                            var lng = "{{ object.location.lng }}"
                                            L.marker([parseFloat(lat), parseFloat(lng)]).addTo(map)
                                            .bindPopup(instLocation)
                                        {% endif %}

                                    };

                            </script>
                        <div style="padding:0;">

                            {% leaflet_map "yourmap" callback="window.map_init_basic" %}

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock custom %}