archiv/urls.py
from django.conf.urls import url
from . import views
from . import tei_views

from archeutils import views as arche_views


app_name = 'archiv'

urlpatterns = [
    url(
        r'^ids$',
        arche_views.get_ids,
        name='get_ids'
    ),
    url(
        r'^arche-title-img$',
        arche_views.get_title_img,
        name='arche_title_img'
    ),
    url(
        r'^arche-md$',
        arche_views.project_as_arche_graph,
        name='arche_md'
    ),
    url(
        r'^archresource/arche/(?P<pk>[0-9]+)$',
        arche_views.res_as_arche_graph,
        name='arche_res'
    ),
    url(
        r'^archresource/$',
        views.ArchResourceListView.as_view(),
        name='archresource_browse'
    ),
    url(
        r'^subject-cloud/$',
        views.subject_cloud,
        name='subject-cloud'
    ),
    url(
        r'^schlagworte/$',
        views.SchlagwortList.as_view(),
        name='schlagworte'
    ),
    url(
        r'^archresource/detail/(?P<pk>[0-9]+)$',
        views.ArchResourceDetailView.as_view(),
        name='archresource_detail'
    ),
    url(
        r'^archresource/create/$',
        views.ArchResourceCreate.as_view(),
        name='archresource_create'
    ),
    url(
        r'^archresource/edit/(?P<pk>[0-9]+)$',
        views.ArchResourceUpdate.as_view(),
        name='archresource_edit'
    ),
    url(
        r'^archresource/delete/(?P<pk>[0-9]+)$',
        views.ArchResourceDelete.as_view(),
        name='archresource_delete'),
    url(
        r'^archresource/xml-tei/(?P<pk>[0-9]+)$',
        tei_views.archres_as_tei,
        name='archresource_xml'
    ),
]

calheatmap/urls.py
from django.urls import include, path
from . import views

app_name = "calheatmap"

urlpatterns = [
    path(
        'data/<app_name>/<model_name>/<field_name>',
        views.calheatmap_data,
        name='calheatmap_data'),
]

entities/urls.py
from django.conf.urls import url
from . import views

app_name = 'entities'

urlpatterns = [
    url(
        r'^person/$',
        views.PersonListView.as_view(),
        name='person_browse'
    ),
    url(
        r'^person/detail/(?P<pk>[0-9]+)$',
        views.PersonDetailView.as_view(),
        name='person_detail'
    ),
    url(
        r'^person/create/$',
        views.PersonCreate.as_view(),
        name='person_create'
    ),
    url(
        r'^person/edit/(?P<pk>[0-9]+)$',
        views.PersonUpdate.as_view(),
        name='person_edit'
    ),
    url(
        r'^person/delete/(?P<pk>[0-9]+)$',
        views.PersonDelete.as_view(),
        name='person_delete'),
    url(
        r'^place/$',
        views.PlaceListView.as_view(),
        name='place_browse'
    ),
    url(
        r'^place/detail/(?P<pk>[0-9]+)$',
        views.PlaceDetailView.as_view(),
        name='place_detail'
    ),
    url(
        r'^place/create/$',
        views.PlaceCreate.as_view(),
        name='place_create'
    ),
    url(
        r'^place/edit/(?P<pk>[0-9]+)$',
        views.PlaceUpdate.as_view(),
        name='place_edit'
    ),
    url(
        r'^place/delete/(?P<pk>[0-9]+)$',
        views.PlaceDelete.as_view(),
        name='place_delete'),
    url(
        r'^institution/$',
        views.InstitutionListView.as_view(),
        name='institution_browse'
    ),
    url(
        r'^institution/detail/(?P<pk>[0-9]+)$',
        views.InstitutionDetailView.as_view(),
        name='institution_detail'
    ),
    url(
        r'^institution/create/$',
        views.InstitutionCreate.as_view(),
        name='institution_create'
    ),
    url(
        r'^institution/edit/(?P<pk>[0-9]+)$',
        views.InstitutionUpdate.as_view(),
        name='institution_edit'
    ),
    url(
        r'^institution/delete/(?P<pk>[0-9]+)$',
        views.InstitutionDelete.as_view(),
        name='institution_delete'),
]

netviz/urls.py
from django.urls import include, path
from . import views

app_name = "netviz"

urlpatterns = [
    path('graph/<app_name>/<model_name>/<pk>', views.graph_data, name='graph'),
    path('graph/<app_name>/<model_name>', views.qs_graph_data, name='qs_as_graph'),
    path('cached/<app_name>/<model_name>', views.cashed_graph_data, name='cached_graph'),
    path('preview/<app_name>/<model_name>', views.preview_graph_data, name='preview_graph'),
    path('<app_name>/<model_name>', views.CachedNetvizView.as_view(), name='cached_graph_html'),
]

vocabs/urls.py
from django.conf.urls import url
from . import views
from . import import_views
from . import dal_views
from .models import SkosLabel, SkosConcept, SkosConceptScheme

app_name = 'vocabs'


urlpatterns = [
    url(r'^$', views.SkosConceptListView.as_view(), name='skosconcept_list'),
    url(r'^concepts/browse/$', views.SkosConceptListView.as_view(), name='browse_vocabs'),
    url(r'^import/$', import_views.import_skos, name='skos_import'),
    url(r'^import-from-csv/$', import_views.import_csv, name='skos_csv_import'),
    url(r'^(?P<pk>[0-9]+)$', views.SkosConceptDetailView.as_view(), name='skosconcept_detail'),
    url(r'^create/$', views.SkosConceptCreate.as_view(), name='skosconcept_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.SkosConceptUpdate.as_view(), name='skosconcept_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SkosConceptDelete.as_view(), name='skosconcept_delete'),
    url(r'^scheme/$', views.SkosConceptSchemeListView.as_view(), name='skosconceptscheme_list'),
    url(
        r'^scheme/(?P<pk>[0-9]+)$', views.SkosConceptSchemeDetailView.as_view(),
        name='skosconceptscheme_detail'),
    url(
        r'^scheme/create/$', views.SkosConceptSchemeCreate.as_view(),
        name='skosconceptscheme_create'),
    url(
        r'^scheme/update/(?P<pk>[0-9]+)$', views.SkosConceptSchemeUpdate.as_view(),
        name='skosconceptscheme_update'),
    url(r'^label/$', views.SkosLabelListView.as_view(), name='skoslabel_list'),
    url(
        r'^label/(?P<pk>[0-9]+)$', views.SkosLabelDetailView.as_view(),
        name='skoslabel_detail'),
    url(
        r'^label/create/$', views.SkosLabelCreate.as_view(),
        name='skoslabel_create'),
    url(
        r'^label/update/(?P<pk>[0-9]+)$', views.SkosLabelUpdate.as_view(),
        name='skoslabel_update'),
]

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    url(r'^$', views.GenericWebpageView.as_view(), name="start"),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^project-info/$', views.project_info, name='project_info'),
    url(r'^(?P<template>[\w-]+)/$', views.GenericWebpageView.as_view(), name='staticpage'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

webpage/views.py
from copy import deepcopy

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout

from . forms import form_user_login
from . metadata import PROJECT_METADATA as PM


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_context_data(self, **kwargs):
        context = super(GenericWebpageView, self).get_context_data(**kwargs)
        context['apps'] = settings.INSTALLED_APPS
        return context

    def get_template_names(self):
        template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        except:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render_to_response('webpage/user_logout.html')


def handler404(request, exception):
    return render(request, 'webpage/404-error.html', locals())


def project_info(request):

    """
    returns a dict providing metadata about the current project
    """

    info_dict = deepcopy(PM)

    if request.user.is_authenticated:
        pass
    else:
        del info_dict['matomo_id']
        del info_dict['matomo_url']
    info_dict['base_tech'] = 'django'
    info_dict['framework'] = 'djangobaseproject'
    return JsonResponse(info_dict)

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <div class="card">

        <div class="card-body">
            <div>
                <h1>Die große Transformation</h1>
                <h3>Das Projekt</h3>
                <p>
                    Anlässlich großer politischer Umbrüche wie des Zerfalls des Habsburgerreichs und der darauffolgenden Entstehung der Ersten Republik liegt es nahe, nach Kontinuitäten und Brüchen in der öffentlichen Verwaltung zu fragen.
                </p>
                <p>
                    Dieses Projekt fokussiert auf die Transformationen, die in den unmittelbar auf das Ende der Monarchie folgenden Jahren auf der Ebene der Verwaltung des Bundes und der Stadt Wien stattfanden. Dabei war die Situation der städtischen Bediensteten weitaus vorteilhafter als jene der staatlichen, die vom Nationalitätenhader in den Nachfolgestaaten, Inflation und Personalabbau massiv betroffen waren.
                </p>
                <p>
                    Die Angelegenheiten der Staatsbediensteten wurden im Zusammenhang mit der Transformation im Staatsrat, im Kabinettsrat und in der Provisorischen Nationalversammlung verhandelt. Der Kabinettsrat setzte ein zwischenstaatsamtliches Komitee für Staatsangestelltenangelegenheiten für konkrete Fragen der Beamten im Zuge der Transformation ein. Dieses Komitee sollte die Schwierigkeiten bereinigen helfen, die durch den Zerfall der Monarchie den Beamten entstanden.
                </p>
                <p>
                    Die Angelegenheiten der Staatsbediensteten wurden im Zusammenhang mit der Transformation im Staatsrat, im Kabinettsrat und in der Provisorischen Nationalversammlung verhandelt. Der Kabinettsrat setzte ein zwischenstaatsamtliches Komitee für Staatsangestelltenangelegenheiten für konkrete Fragen der Beamten im Zuge der Transformation ein. Dieses Komitee sollte die Schwierigkeiten bereinigen helfen, die durch den Zerfall der Monarchie den Beamten entstanden.
                </p>
                <p>
                    Bedienstete des Bundes ebenso wie solche der Stadt Wien mussten anstelle des früheren Diensteids ein neues Gelöbnis auf die Republik ablegen. Die Gelöbnisformel wurde einige Male abgeändert. Bei der Gestaltung der neuen Dienstordnung der Bediensteten der Stadt Wien, die im April 1919 beschlossen wurde, waren Gemeinderäte ebenso wie Vertreter_innen unterschiedlicher Angestelltengruppen einbezogen. Eine moderne, demokratisierte Verwaltung war ein Anliegen der Stadt Wien. Die Stadtpolitiker konnten auf dem Wahlerfolg der Sozialdemokratischen Partei bei der Gemeinderatswahl im Mai 1919 aufbauen. Dieser war auch die maßgebliche Zäsur für die Verwaltung der Stadt Wien in Bezug auf die nun endgültig obsolete „Lueger-Ära“. Trotz der besseren Bezahlung im Vergleich mit den Bundesbeamten mussten sehr oft Teuerungszulagen ausverhandelt werden, um den Bediensteten der Stadt Wien den Lebensunterhalt zu sichern.
                </p>
                <h3>Die Datenbank</h3>
                <p>
                    Die Datenbank des Projekts „Die große Transformation“ versammelt relevante Quellen aus unterschiedlichen Archiven zu Fragen der Reform der Bundes- und Wiener Gemeindeverwaltung in der unmittelbaren Nachkriegszeit 1918 bis 1920. Der in der Datenbank edierte Quellenkorpus umfasst untenstehende Bestände und erlaubt erstmals in komparativer Perspektive einen Blick auf die Zusammenhänge in der Transformation der beiden Verwaltungsebenen durch die Republiksgründung. Die aus den Quellen erstellten Datensätze wurden beschlagwortet und die in ihnen erwähnten Personen, Institutionen und Orte erfasst. Darüber hinaus wurden die Quellen durch Beschreibungen und Inhaltsangaben versehen. Sie sind damit umfassend durchsuchbar. Wo möglich, werden ihnen Digitalisate bzw. Permalinks zu Digitalisaten beigestellt. Durch die zusätzliche Erfassung von Normdaten bei Personen und Orten ist die Anknüpfung an andere Datenbanken möglich und somit eine nachhaltige Verwendung sichergestellt.
                </p>
                <h3>Erfasste Bestände</h3>
                <p>
                    In der Datenbank erfasste Bestände:
                    <ul>
                        <li>
                            Verhandlungsschriften (Komitee Staatsangestellte)
                        </li>
                        <li>
                            Enquete (Zielrichtung mehr Mitbestimmung, Personalvertretung)
                        </li>
                        <li>
                            Relevante Akte Staatsrat und Kabinettsrat
                        </li>
                        <li>
                            Relevante Gesetze (Staatsgesetzblatt)
                        </li>
                        <li>
                            Zeitungen, Zeitschriften
                        </li>
                        <li>
                            Akten der Allgemeinen Registratur der Magistratsdirektion, Wiener Stadt- und Landesarchiv
                        </li>
                        <li>
                            Gemeinderats- und Stadtratsprotokolle wie in den Amtsblättern der Stadt Wien veröffentlicht
                        </li>
                        <li>
                            Akten des Parteiarchivs vor 1934 der SDAP, Verein der Geschichte der Arbeiterbewegung in Wien (VGA)
                        </li>
                        <li>
                            Tagblattarchiv zum Stichwort Beamten, Wienbibliothek
                        </li>
                        <li>
                            ÖGB-Archiv, Material zu Beamtenorganisationen
                        </li>
                    </ul>
                    Die Bestände werden gegenwärtig (Stand 10. Oktober 2018) erweitert.
                </p>
                <p>
                    Das Projekt wird finanziert durch den <a href="https://www.wien.gv.at/kultur/abteilung/wissenschaftsfonds/akademie-wissenschaften.html">Jubiläumsfonds der Stadt Wien für die Österreichische Akademie der Wissenschaften</a>.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load static %}
{% load webpage_extras %}
{% load browsing_extras %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'webpage/img/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'webpage/img/favicon/favicon-32x32.png' %}"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'webpage/img/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'webpage/img/favicon/manifest.json' %}"/>
        <link rel="mask-icon" href="{% static 'webpage/img/favicon/safari-pinned-tab.svg' %}" color="#00aba9"/>
        <meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'webpage/css/fundament.css' %}" rel="stylesheet"/>
    <!-- <link rel="stylesheet" href="{% static 'webpage/css/fundament_new.css' %}" rel="stylesheet"/> -->
    <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}" />
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% projects_metadata 'imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- Matomo -->
      <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="{% projects_metadata 'matomo_url' %}";
          _paq.push(['setTrackerUrl', u+'piwik.php']);
          _paq.push(['setSiteId', '{% projects_metadata "matomo_id" %}']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
      <script src="https://unpkg.com/feather-icons"></script>
    <!-- End Matomo Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="document" class="contained fixed-nav">
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top bg-white box-shadow">
            <a class="navbar-brand" href="/">
                GTrans
            </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                     <ul class="navbar-nav mr-auto">
                     <!-- <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span>
                        </a>
                    </li> -->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Info
                            <span class="caret"/>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'webpage:staticpage' template='about' %}">Über das Projekt</a>
                            <a class="dropdown-item" href="{% url 'webpage:staticpage' template='team' %}">Team</a>
                            <a class="dropdown-item" href="/api">API</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                            {% if user.is_authenticated %}
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Stöbern und Kuratieren
                            <span class="caret"/>
                            </a>
                            {% else %}
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Stöbern
                            <span class="caret"/>
                            </a>
                            {% endif %}
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'archiv:archresource_browse' %}">Dokumente</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'entities:person_browse' %}">Personen</a>
                                <a class="dropdown-item" href="{% url 'entities:institution_browse' %}">Institutionen</a>
                                <a class="dropdown-item" href="{% url 'entities:place_browse' %}">Orte</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'transkribus:trp_search' %}">Faksimiles (Volltextsuche)</a>
                                <a class="dropdown-item" href="{% url 'transkribus:trp_docs' %}">Faksimiles (Liste)</a>
                            </div>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Schlagwörter
                        <span class="caret"/>
                        </a>
                            <div class="dropdown-menu">
                                {% nav_menu app='vocabs' as links %}
                                {% for x in links %}
                                    <a class="dropdown-item" href="{{ x.link }}">Schlagwörter</a>
                                {% endfor %}
                                <a class="dropdown-item" href="{% url 'vocabs:skoslabel_list' %}">Synonyme</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                        {% endif %}

                    </ul>
                    <form class="form-inline mt-2 mt-md-0" style="margin: .5rem;" method="get" action="/search">
                        <input name="q" class="form-control mr-sm-2" type="text" placeholder="Über alle Felder suchen" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Suchen</button>
                    </form>
                    <div class="navbar-icons">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'webpage:user_logout' %}"><small>Log-Out <br / />{{ user.get_username }}</small></a>
                        {% else %}
                            <a class="nav-link" href="{% url 'webpage:user_login' %}">
                                <i class="fas fa-sign-in-alt"></i>
                            </a>
                        {% endif %}
                    </div>
                </nav>
            </header>
<section class="main-content">
    {% if DEV_VERSION %}
    <div class="alert alert-danger" role="alert">
        This is a the DEVELOPMENT instance. Click <a href="https://gtrans.acdh.oeaw.ac.at">here</a> for the Production version
    </div>
    {% endif %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</section>
    <footer class="main-footer">
        <div class="container">
          <div class="footer-wrapper">
            <div class="footer-sep">
              <i class="far fa-comment"></i> CONTACT
            </div>
            <div class="row">
              <div class="col-md-2 pl-0">
                <a href="https://www.oeaw.ac.at/acdh/" target="_blank" rel="noopener" aria-label="ACDH-CH">
                  <img src="https://shared.acdh.oeaw.ac.at/acdh-common-assets/images/acdh-ch-logo-grayscale.png" alt="ACDH-CH" title="Austrian Centre for Digital Humanities and Cultural Heritage" style="max-height: 4em;"/>
                </a>
              </div>
              <div class="col-md-2 ml-auto">
                  <img src="{% static 'webpage/img/uni_logo.png' %}" alt="Logo Universität Wien" title="Logo Universität Wien"/>
              </div>
              </div>

            </div>
          </div>
        </div>
        <div class="footer-imprint-bar">
            <a href="{% projects_metadata 'imprint' %}">Impressum/Imprint</a>
            {% social_media %}
            {% if user.is_authenticated %}
                {% if DB_NAME %}
                    <div class="footer-imprint-bar">
                        <small>{{ DB_NAME }}</small>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </footer>
    {% block scripts %}
    <script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/vendor/js/fontawesome-all.min.js"></script>
    <script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/js/fundament.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css" />
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $.apScrollTop({'onInit': function(evt) {console.log('apScrollTop: init');}});
        });
    </script>
    <script>
        feather.replace()
    </script>
    {% endblock %}
    {% block scripts2 %}
    {% endblock scripts2 %}
    <noscript>
        <img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=48" style="border:0;" alt=""/>
    </noscript>
    </body>
    </html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn" type="submit" value="No, bring me back" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
</div>
{% endblock %}

webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}
{% block title %}logout{% endblock %}
{% block content %}
<div class="container">
    <h1>Sayōnara!</h1>
    <p>You've logged out</p>
</div>
{% endblock content %}